"""add destination fees

Revision ID: 02080dea7bac
Revises: 50953badb5c6
Create Date: 2026-03-19 18:17:41.482569
"""
from alembic import op
import sqlalchemy as sa


revision = '02080dea7bac'
down_revision = '50953badb5c6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('destinations', sa.Column('peak_fee_usd', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('destinations', sa.Column('low_fee_usd', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('destinations', 'low_fee_usd')
    op.drop_column('destinations', 'peak_fee_usd')
    # ### end Alembic commands ###
