"""add_safari_availability

Revision ID: 47f9f562a34e
Revises: e79f5a13b9ee
Create Date: 2026-03-19 22:17:47.759785
"""
from alembic import op
import sqlalchemy as sa


revision = '47f9f562a34e'
down_revision = 'e79f5a13b9ee'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
