"""add promo_code to bookings

Revision ID: 8304c411a313
Revises: 47f9f562a34e
Create Date: 2026-03-22 22:55:01.943537
"""
from alembic import op
import sqlalchemy as sa


revision = '8304c411a313'
down_revision = '47f9f562a34e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('promo_code', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'promo_code')
    # ### end Alembic commands ###
