"""add_is_shared_to_safaris

Revision ID: a4272217c3d6
Revises: 8304c411a313
Create Date: 2026-03-24 01:51:32.211130
"""
from alembic import op
import sqlalchemy as sa


revision = 'a4272217c3d6'
down_revision = '8304c411a313'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('safaris', sa.Column('is_shared', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('safaris', 'is_shared')
    # ### end Alembic commands ###
