"""add partner_lodges and safari beach extension

Revision ID: e79f5a13b9ee
Revises: 02080dea7bac
Create Date: 2026-03-19 18:34:44.748145
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'e79f5a13b9ee'
down_revision = '02080dea7bac'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('partner_lodges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=False),
    sa.Column('destination_slug', sa.String(length=100), nullable=False),
    sa.Column('tier', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('amenities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('price_usd_per_night', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('commission_pct', sa.Integer(), nullable=False),
    sa.Column('booking_email', sa.String(length=200), nullable=True),
    sa.Column('website_url', sa.String(length=500), nullable=True),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.add_column('safaris', sa.Column('has_beach_extension', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('safaris', sa.Column('beach_extension_days', sa.Integer(), nullable=True))
    op.add_column('safaris', sa.Column('beach_extension_price_usd', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('safaris', sa.Column('beach_extension_price_kes', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('safaris', sa.Column('beach_extension_desc', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('safaris', 'beach_extension_desc')
    op.drop_column('safaris', 'beach_extension_price_kes')
    op.drop_column('safaris', 'beach_extension_price_usd')
    op.drop_column('safaris', 'beach_extension_days')
    op.drop_column('safaris', 'has_beach_extension')
    op.drop_table('partner_lodges')
    # ### end Alembic commands ###
